spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/caycanhdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
app.jwt.secret=change-this-jwt-secret-key-for-dev-only-please-replace-123456789
app.jwt.expiration-ms=3600000
app.jwt.reset-password-expiration-ms=900000
app.jwt.cookie.name=access_token
app.jwt.cookie.path=/api
app.jwt.cookie.domain=localhost
app.jwt.cookie.secure=false
app.jwt.cookie.same-site=Strict
app.auth.reset-password.url=http://localhost:3000/reset-password
app.auth.oauth2.redirect-url=http://localhost:3000
app.auth.oauth2.use-cookie-redirect=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.show-actuator=false
springdoc.model-converters.deprecation-converter.enabled=true
springdoc.remove-broken-model-converters=true

cloudinary.cloud-name=dtaabsu53
cloudinary.api-key=166112671383171
cloudinary.api-secret=zddcgpvagPyTpcHrGW5v7qBSgQU

vnpay.vnp_TmnCode=3OGDDTKI
vnpay.vnp_HashSecret=DJ6O1DNJFDRFS3P88VJVSLYS9MRD2STF
vnpay.vnp_PayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.vnp_ReturnUrl=http://localhost:3000/payment/vnpay-return

# IMPORTANT redirect URI in Google Console:
# http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-id=546930077222-innofokbakhqo3kldar18koh68o4l5ov.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phamminhduc15112003dilinh@gmail.com
spring.mail.password=yglpgdlyhkybrnuu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.main.allow-circular-references=true

#
#
#
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/caycanhdb}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
#app.jwt.secret=change-this-jwt-secret-key-for-dev-only-please-replace-123456789
#app.jwt.expiration-ms=3600000
#app.jwt.reset-password-expiration-ms=900000
#app.jwt.cookie.name=access_token
#app.jwt.cookie.path=/api
#app.jwt.cookie.domain=160.250.181.24
#app.jwt.cookie.secure=false
#app.jwt.cookie.same-site=Strict
#app.auth.reset-password.url=http://160.250.181.24:3000/reset-password
#app.auth.oauth2.redirect-url=http://160.250.181.24:3000
#app.auth.oauth2.use-cookie-redirect=true
#
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.operations-sorter=method
#springdoc.swagger-ui.tags-sorter=alpha
#springdoc.show-actuator=false
#springdoc.model-converters.deprecation-converter.enabled=true
#springdoc.remove-broken-model-converters=true
#
#cloudinary.cloud-name=dtaabsu53
#cloudinary.api-key=166112671383171
#cloudinary.api-secret=zddcgpvagPyTpcHrGW5v7qBSgQU
#
#vnpay.vnp_TmnCode=3OGDDTKI
#vnpay.vnp_HashSecret=DJ6O1DNJFDRFS3P88VJVSLYS9MRD2STF
#vnpay.vnp_PayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.vnp_ReturnUrl=http://160.250.181.24:3000/payment/vnpay-return
#
## IMPORTANT redirect URI in Google Console:
## http://localhost:8080/login/oauth2/code/google
#spring.security.oauth2.client.registration.google.client-id=546930077222-innofokbakhqo3kldar18koh68o4l5ov.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#spring.security.oauth2.client.registration.google.redirect-uri=http://160.250.181.24:8080/login/oauth2/code/google
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=phamminhduc15112003dilinh@gmail.com
#spring.mail.password=yglpgdlyhkybrnuu
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.main.allow-circular-references=true
